### ISSUE TITLE
Create an html page that will be the main game page

### ISSUE THREAD

**Issue by tndmohawk** [the-new-developers/gatehopper#17]
## Summary:
We need an html page that will hold all of the DOM elements of our game, and which our game engine will use to populate the logic gates and read user input, etc. 

For now, this page can just have some placeholder text, for example "This is the main game page."

## Unresolved questions:
What should the name of this page be? `game.html` is ok, but might be too vague?

**Comment by VictorSohier** [comment]
Might this possibly be a duplicate with #14 ?

**Comment by rodneybarnes** [comment]
Closing as we will be using p5js to manage the various screens that the player will see, so separate `html` files are not necessary.
