### ISSUE TITLE
Each level starts with 3-second countdown

### ISSUE THREAD

**Issue by WaelHarba** [the-new-developers/gatehopper#30]
## Summary:
Countdown in [the JavaScript file](https://github.com/the-new-developers/gatehopper/issues/20) that'll show up once a level loads.
This countdown will indicate to when the timer of a level should start.

## The related PR must:

- [ ] Display a countdown that covers the entire display, preventing the user from seeing or interacting with anything else
- [ ] Once the countdown has finished, the user should be able to see and interact again with the game

**Comment by VictorSohier** [comment]
This might be better off as one of those configurable things in the settings menu as a fixed 3 seconds for people who become good at the game then would then be waiting more than actually playing the game.
