### ISSUE TITLE
What are we working on? 

### ISSUE THREAD

**Issue by j0eTheRipper** [the-new-developers/gatehopper#34]
# tl;dr
What are we working on? 

# We need to know what we are working on.
as of when I'm typing the message, we're 35 people working on a project on github, with an index.html file and a usless Readme.md file
we need to know at least what type of project we're workin on.

**Comment by WaelHarba** [comment]
Hey @j0eTheRipper!

For further information on what's being developed, please check [Project Foobar](https://thenewdevelopers.com/2021-04-25-project-foobar/) on [The New Developers](https://thenewdevelopers.com/) website.

There are also two dedicated channels for this project on a Discord server for The New Developers: `🔉 Foobar Voice` for voice chatting about this project, and `#foobar-text` for texting about this project.
If you want to use these dedicated channels to ask questions and join meetings, feel free to join The New Developers [Discord server](https://bit.ly/tnd-discord).
Please check the pinned messages in `#foobar-text` if end up joining the server.
