### ISSUE TITLE
Implement user input for the game

### ISSUE THREAD

**Issue by VictorSohier** [the-new-developers/gatehopper#46]
Ultimately, this is a game and it isn't really a game without user input.

**Comment by WaelHarba** [comment]
Do you think this might be a duplicate with #42 ? Both talk about the fact that user need to be able to submit an answer which means implementing user input.

**Comment by VictorSohier** [comment]
> Do you think this might be a duplicate with #42 ? Both talk about the fact that user need to be able to submit an answer which means implementing user input.

Mustn't have seen it. Thank you for bringing this to my attention.
